# Stage 1
FROM node:18-alpine as builder
WORKDIR /app
COPY ./ui/package*.json ./ui/yarn*.lock ./
RUN yarn install
COPY ./ui ./
RUN yarn build

# Stage 2
FROM nginx:1.19.0
WORKDIR /usr/share/nginx/html
RUN rm -rf ./*
COPY --from=builder /app/build .

EXPOSE 8080

ENTRYPOINT ["nginx", "-g", "daemon off;"]
